-- SparkNC D1 intelligence layer for Sprint 4
PRAGMA foreign_keys = ON;

-- Student insights generated by the intelligence engine
CREATE TABLE IF NOT EXISTS student_insights (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL,
  insight_type TEXT NOT NULL,
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  priority TEXT NOT NULL DEFAULT 'normal',
  data TEXT,
  created_at TEXT NOT NULL,
  expires_at TEXT,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_student_insights_user ON student_insights(user_id);
CREATE INDEX IF NOT EXISTS idx_student_insights_type ON student_insights(user_id, insight_type);

-- Growth timeline events
CREATE TABLE IF NOT EXISTS growth_events (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL,
  event_type TEXT NOT NULL,
  title TEXT NOT NULL,
  description TEXT,
  occurred_at TEXT NOT NULL,
  metadata TEXT,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_growth_events_user ON growth_events(user_id);
CREATE INDEX IF NOT EXISTS idx_growth_events_occurred ON growth_events(user_id, occurred_at);

-- Achievements / badges
CREATE TABLE IF NOT EXISTS achievements (
  id TEXT PRIMARY KEY,
  achievement_key TEXT NOT NULL UNIQUE,
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  category TEXT NOT NULL,
  criteria TEXT NOT NULL,
  points INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_achievements_key ON achievements(achievement_key);
CREATE INDEX IF NOT EXISTS idx_achievements_category ON achievements(category);

-- Unlocked achievements per user
CREATE TABLE IF NOT EXISTS user_achievements (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL,
  achievement_id TEXT NOT NULL,
  unlocked_at TEXT NOT NULL,
  metadata TEXT,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (achievement_id) REFERENCES achievements(id) ON DELETE CASCADE,
  UNIQUE (user_id, achievement_id)
);

CREATE INDEX IF NOT EXISTS idx_user_achievements_user ON user_achievements(user_id);
CREATE INDEX IF NOT EXISTS idx_user_achievements_achievement ON user_achievements(achievement_id);

-- Personal records per user
CREATE TABLE IF NOT EXISTS personal_records (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL,
  record_type TEXT NOT NULL,
  record_value REAL NOT NULL,
  record_unit TEXT,
  recorded_at TEXT NOT NULL,
  metadata TEXT,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  UNIQUE (user_id, record_type)
);

CREATE INDEX IF NOT EXISTS idx_personal_records_user ON personal_records(user_id);

-- Organization/school analytics snapshots
CREATE TABLE IF NOT EXISTS analytics_snapshots (
  id TEXT PRIMARY KEY,
  scope TEXT NOT NULL,
  scope_id TEXT,
  snapshot_type TEXT NOT NULL,
  snapshot_date TEXT NOT NULL,
  metrics TEXT NOT NULL,
  created_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_analytics_snapshots_scope ON analytics_snapshots(scope, scope_id);
CREATE INDEX IF NOT EXISTS idx_analytics_snapshots_type ON analytics_snapshots(snapshot_type, snapshot_date);

-- AI companion short-term memory
CREATE TABLE IF NOT EXISTS ai_memories (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL,
  role TEXT NOT NULL,
  content TEXT NOT NULL,
  context TEXT,
  created_at TEXT NOT NULL,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_ai_memories_user ON ai_memories(user_id);
CREATE INDEX IF NOT EXISTS idx_ai_memories_created ON ai_memories(user_id, created_at);

-- Audit log for sensitive actions
CREATE TABLE IF NOT EXISTS audit_logs (
  id TEXT PRIMARY KEY,
  actor_id TEXT,
  action TEXT NOT NULL,
  entity_type TEXT,
  entity_id TEXT,
  metadata TEXT,
  created_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_audit_logs_actor ON audit_logs(actor_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_entity ON audit_logs(entity_type, entity_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_created ON audit_logs(created_at);

-- Ambassador to student assignments
CREATE TABLE IF NOT EXISTS ambassador_assignments (
  id TEXT PRIMARY KEY,
  ambassador_id TEXT NOT NULL,
  student_id TEXT NOT NULL,
  created_at TEXT NOT NULL,
  FOREIGN KEY (ambassador_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (student_id) REFERENCES users(id) ON DELETE CASCADE,
  UNIQUE (ambassador_id, student_id)
);

CREATE INDEX IF NOT EXISTS idx_ambassador_assignments_ambassador ON ambassador_assignments(ambassador_id);
CREATE INDEX IF NOT EXISTS idx_ambassador_assignments_student ON ambassador_assignments(student_id);

-- Seed default achievements
INSERT OR IGNORE INTO achievements (id, achievement_key, title, description, category, criteria, points, created_at) VALUES
('ach_first_goal', 'first_goal', 'First Goal Completed', 'Complete your first goal.', 'goals', '{"goalsCompleted": 1}', 10, CURRENT_TIMESTAMP),
('ach_7_day_streak', '7_day_streak', '7 Day Streak', 'Maintain a 7-day activity streak.', 'streaks', '{"streakDays": 7}', 15, CURRENT_TIMESTAMP),
('ach_30_day_streak', '30_day_streak', '30 Day Streak', 'Maintain a 30-day activity streak.', 'streaks', '{"streakDays": 30}', 50, CURRENT_TIMESTAMP),
('ach_event_participant', 'event_participant', 'Event Participant', 'Register for a SparkNC event.', 'events', '{"eventsAttended": 1}', 10, CURRENT_TIMESTAMP),
('ach_community_helper', 'community_helper', 'Community Helper', 'Send 10 messages to other students.', 'messages', '{"messagesSent": 10}', 15, CURRENT_TIMESTAMP),
('ach_level_5', 'level_5', 'Reaching Level 5', 'Earn 5 levels through XP.', 'levels', '{"level": 5}', 25, CURRENT_TIMESTAMP);
